### ISSUE TITLE
Deploy using Google Autopilot

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#254]
Look into using https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview as a way to deploy the Plone and Volto containers, along with the Google Load Balancer.

Note that the latter may need to do rewriting of the Plone /api calls and proxying to the Plone backend.

**Comment by ajtucker** [comment]
- [ ] cloudbuild.yaml created in branch for automated building of Docker images and upload to private registry.
- [ ] updates roll out using e.g. `kubectl rollout restart deployment volto`
- [ ] HTTPS: Google Load Balancer or nginx & certbot
- [ ] database / volume persistence

Optimisation
- [ ] cache build using [Kanico](https://cloud.google.com/build/docs/optimize-builds/kaniko-cache)
- [ ] Use gitops style split with two repos: dd-cms and ccv2-env

**Comment by ajtucker** [comment]
Issue was closed automatically by merging #556. Re-opening as there are outstanding issues.
