### ISSUE TITLE
End user style/content fixes

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#295]
- [x] Decide on max width for `volto-width-container--wide`
- [x] #352
- [x] #353  Breadcrumbs to have background of masthead
- [x] Don't need "home" in navbar menu
- [x] Article attribution full names showing up as user IDs, e.g. "by 2bdc1d87-83ae-4549-8ebf-Ffdd7eb572ee" #351
- [ ] #355   RSS should be an easy one!
- [x] #354   Main text in blocks seems a bit small -- check the default styles match designs
- [x] Underlining in first heading

**Comment by ajtucker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cogs-dd-cms-61e83b63053eb70011d37b4f/issues/GSS-Cogs/dd-cms/295?planning-poker) with ZenHub @nosnickid @charlesons

**Comment by charlesons** [comment]
On the phase banner, [gov.uk guidance](https://design-system.service.gov.uk/components/phase-banner/) states that:

_Services hosted on a service.gov.uk domain must use the phase banner until they pass a live assessment.

Use an alpha banner when your service is in alpha, and a beta banner if your service is in private or public beta._

**Comment by TahaRana97** [comment]
This task is a nice to have - will need to verify functionality as required
