### ISSUE TITLE
Climate Change mock up

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/dd-cms#3]
The [Climate Change website](https://climate-change.data.gov.uk) consists of a number of articles and detailed explanations of the UK's climate change "indicators", with the main innovation being that all the charts and figures are rendered on the fly from published linked open data, (mostly) using SPARQL to pull out the required data points.

We can use this site as a way to derive requirements for a CMS and mock up an equivalent website to prototype some use cases.

- [x] Spin up Plone + Volto
- [x] Use [govuk-react](https://github.com/govuk-react/govuk-react) to style up the Volto front end. #4 
- [x] Try some of the [plugins developed for the European Environment Agency](https://github.com/eea), e.g. [volto-slate](https://github.com/eea/volto-slate), [volto-datablocks](https://github.com/eea/volto-datablocks), [volto-plotlycharts](https://github.com/eea/volto-plotlycharts).

## Acceptance

As an analyst, I should be able to log in, create an article, add and edit the body of the article, upload some supporting data as CSV and add a chart based on this data.
