### ISSUE TITLE
Tweak dashboard tile header and footer text color

### ISSUE THREAD

**Issue by charlesons** [GSS-Cogs/dd-cms#317]
- [ ] Category text colour: #505A5F
- [ ] Title text color: #0B0C0C
- [ ] Footer link text: #1D70B8
