### ISSUE TITLE
Topics and Sub-topics Requirements Gathering

### ISSUE THREAD

**Issue by edd-harvey** [GSS-Cogs/dd-cms#893]
### Description
We need to validate the topics we have chosen for the home page of the Data Explorer, determine a list of sub-topics that sit within each of those topics and map the current datasets in PMD to those sub-topics and topics.

### Problem

We are trying to come up with a list of topics and sub-topics that will make sense and make it easy for analysts to align their datasets to the relevant topic / sub-topic. The problem of topics, taxonomy and sub-topics have been known through UR and various other feedback for a while. With users being impacted by finding it hard to find the datasets they are interested in.

### Appetite
At the moment we just want to answer the questions listed in the tasks section below

### Opportunities
Have a consolidate and validated list of topics and sub-topics that would meet the majority of most publishers needs

### Rabbit Holes / No Goes
Do a full blown review of taxonomy and topics, we're validating what we think is a first good attempt

### Source
UR done on the Data Explorer prototype

### User Story
**As a** user of the data explorer 
**I want a** list of topics on the home page
**So that** I can browse the topic I'm interested in

**As a** user of the data explorer 
**I want a** list of sub-topics when I click into a topic
**So that** I can browse the sub-topics I'm interested in

### Tasks
- [x] Review UKSA topics against GOV.UK and ONS topics to see if their topics match up with the [UKSA Topics](https://uksa.statisticsauthority.gov.uk/domains/health-social-care/) (Domains on the left are topics), [GOV.UK Home Page](https://www.gov.uk/) (topics on home page) and [ONS home page](https://www.ons.gov.uk/) (topics in the header at the top of the site) - do they align? We've decided to go with the UKSA domains as the topics for the home page of the data explorer, but are we missing any topics we think are important?

- [x] Generate a list of sub-topics through analysis / reviewing UKSA, GOV.UK and ONS website to generate list of sub topics for each high level topic - may need to engage and liase with publishers / producers / working groups?

- [ ] Review the datasets in PMD and marry them up to the newly created sub-topics and UKSA high level topics
Speak to Harry whose already begun working on this
